function(salt_booklamp_default_assemble_rule target)
    set(inputVar "${MP_CC};-c;${MP_EXTRA_AS_PRE};-mcpu=16F15213;-mdfp=C:/Users/fernau/.mchp_packs/Microchip/PIC16F1xxxx_DFP/1.24.387/xc8;-fshort-double;-fshort-float;-memi=wordwrite;-O0;-maddrqual=require;-mwarn=-3;-Wa,-a;-DXPRJ_default=default;-msummary=-psect,-class,+mem,-hex,-file;-ginhx32;-Wl,--data-init;-mno-keep-startup;-mno-osccal;-moscval=0x3400;-mno-download;-mno-stackcall;-mno-default-config-bits;-std=c90;-gdwarf-3;-mstack=compiled:auto:auto:auto;${INSTRUMENTED_TRACE_OPTIONS}")
    string(REGEX REPLACE "[,]+" "," noDoubleCommas "${inputVar}")
    string(REGEX REPLACE ",$" "" noDanglingCommas "${noDoubleCommas}")
    target_compile_options(${target} PRIVATE "${noDanglingCommas}")
endfunction()
function(salt_booklamp_default_assemblePreprocess_rule target)
    set(inputVar "-c;${MP_EXTRA_AS_PRE};-mcpu=16F15213;-mdfp=C:/Users/fernau/.mchp_packs/Microchip/PIC16F1xxxx_DFP/1.24.387/xc8;-fshort-double;-fshort-float;-memi=wordwrite;-O0;-maddrqual=require;-mwarn=-3;-Wa,-a;-DXPRJ_default=default;-msummary=-psect,-class,+mem,-hex,-file;-ginhx32;-Wl,--data-init;-mno-keep-startup;-mno-osccal;-moscval=0x3400;-mno-download;-mno-stackcall;-mno-default-config-bits;-std=c90;-gdwarf-3;-mstack=compiled:auto:auto:auto;${INSTRUMENTED_TRACE_OPTIONS}")
    string(REGEX REPLACE "[,]+" "," noDoubleCommas "${inputVar}")
    string(REGEX REPLACE ",$" "" noDanglingCommas "${noDoubleCommas}")
    target_compile_options(${target} PRIVATE "${noDanglingCommas}")
endfunction()
function(salt_booklamp_default_compile_rule target)
    set(inputVar "${MP_CC};${MP_EXTRA_CC_PRE};-mcpu=16F15213;-c;-mdfp=C:/Users/fernau/.mchp_packs/Microchip/PIC16F1xxxx_DFP/1.24.387/xc8;-fshort-double;-fshort-float;-memi=wordwrite;-O0;-maddrqual=require;-mwarn=-3;-Wa,-a;-DXPRJ_default=default;-msummary=-psect,-class,+mem,-hex,-file;-ginhx32;-Wl,--data-init;-mno-keep-startup;-mno-osccal;-moscval=0x3400;-mno-download;-mno-stackcall;-mno-default-config-bits;-std=c90;-gdwarf-3;-mstack=compiled:auto:auto:auto;${INSTRUMENTED_TRACE_OPTIONS};${FUNCTION_LEVEL_PROFILING_OPTIONS}")
    string(REGEX REPLACE "[,]+" "," noDoubleCommas "${inputVar}")
    string(REGEX REPLACE ",$" "" noDanglingCommas "${noDoubleCommas}")
    target_compile_options(${target} PRIVATE "${noDanglingCommas}")
endfunction()
function(salt_booklamp_default_link_rule target)
    set(inputVar "${MP_EXTRA_LD_PRE};-mcpu=16F15213;-Wl,-Map=mem.map;-DXPRJ_default=default;-Wl,--defsym=__MPLAB_BUILD=1;-mdfp=C:/Users/fernau/.mchp_packs/Microchip/PIC16F1xxxx_DFP/1.24.387/xc8;-fshort-double;-fshort-float;-memi=wordwrite;-O0;-maddrqual=require;-mwarn=-3;-Wa,-a;-msummary=-psect,-class,+mem,-hex,-file;-ginhx32;-Wl,--data-init;-mno-keep-startup;-mno-osccal;-moscval=0x3400;-mno-download;-mno-stackcall;-mno-default-config-bits;-std=c90;-gdwarf-3;-mstack=compiled:auto:auto:auto;${INSTRUMENTED_TRACE_OPTIONS};${FUNCTION_LEVEL_PROFILING_OPTIONS};-Wl,--memorysummary,memoryfile.xml,")
    string(REGEX REPLACE "[,]+" "," noDoubleCommas "${inputVar}")
    string(REGEX REPLACE ",$" "" noDanglingCommas "${noDoubleCommas}")
    target_link_options(${target} PRIVATE "${noDanglingCommas}")
endfunction()
